# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='shortContent',
            field=models.TextField(default='asdasda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='revisedTime',
            field=models.TextField(),
        ),
    ]
