# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_auto_20170114_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='skblog',
            name='revisedId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skblog',
            name='revisedTime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
